# Generated by Django 4.0.3 on 2022-10-05 00:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotAdmins',
            fields=[
                ('USER_ID', models.IntegerField(blank=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LEVEL', models.IntegerField(blank=True, verbose_name='LEVEL')),
            ],
        ),
        migrations.CreateModel(
            name='Profile_users',
            fields=[
                ('workersID', models.IntegerField(blank=True, primary_key=True, serialize=False, verbose_name='WorkerID')),
                ('ADRESS', models.CharField(blank=True, max_length=100, verbose_name='ADRESS')),
                ('FULLNAME', models.CharField(blank=True, max_length=100, verbose_name='FULLNAME')),
                ('PROFILE', models.CharField(blank=True, max_length=40, verbose_name='Name Of Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Urls',
            fields=[
                ('ID', models.IntegerField(blank=True, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('COST', models.IntegerField(default='100', verbose_name='COST')),
                ('URLS', models.CharField(blank=True, max_length=100, verbose_name='urls')),
                ('DATA_TIME', models.DateField(default=datetime.date.today)),
                ('ADRESS', models.CharField(blank=True, max_length=100, verbose_name='ADRESS')),
                ('FULLNAME', models.CharField(blank=True, max_length=100, verbose_name='FULLNAME')),
                ('NICKNAME', models.CharField(default='Anonymous', max_length=100, verbose_name='Telegram nickname')),
                ('IMAGEURLS', models.CharField(default='', max_length=500, verbose_name='Image Url')),
            ],
        ),
        migrations.CreateModel(
            name='Workers',
            fields=[
                ('ID', models.IntegerField(blank=True, primary_key=True, serialize=False, verbose_name='UserID')),
                ('NAME', models.CharField(blank=True, max_length=100, verbose_name='data-time')),
                ('DATATIME', models.DateField(default=datetime.date.today)),
                ('SALE', models.IntegerField(blank=True, default=0, verbose_name='SALE')),
                ('BALANCE', models.CharField(blank=True, max_length=100, verbose_name='BALANCE')),
                ('COUNTERT', models.IntegerField(blank=True, default=0, verbose_name='CounterOfTrues')),
                ('COUNTERW', models.IntegerField(blank=True, default=0, verbose_name='CounterOfWins')),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bin', models.CharField(max_length=100, verbose_name='BIN')),
                ('cvv', models.CharField(max_length=10, verbose_name='CVV')),
                ('money_on_card', models.IntegerField(blank=True, verbose_name='Money')),
                ('full_name', models.CharField(max_length=300, verbose_name='FULL NAME')),
                ('workers', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.workers')),
            ],
        ),
    ]
