# Generated by Django 4.0.3 on 2022-10-05 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urls',
            name='NICKiTEM',
            field=models.CharField(default='Anonymous', max_length=100, verbose_name='Name Item'),
        ),
        migrations.AlterField(
            model_name='urls',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID TELEGRAM'),
        ),
    ]
