# Generated by Django 4.0.3 on 2022-10-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_urls_nickitem_alter_urls_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='datatimefield',
            field=models.CharField(default='None', max_length=20, verbose_name='Data Card'),
        ),
    ]
